import siteSettings from './siteSettings'
import service from './service'
import project from './project'
import testimonial from './testimonial'
import hero from './hero'
import about from './about'
import cta from './cta'
import team from './team'
import homePage from './homePage'
import catalog from './catalog'
import productCategory from './productCategory'
import product from './product'
import inquiry from './inquiry'
import businessNiche from './businessNiche'

export const schemaTypes = [siteSettings, service, project, testimonial, hero, about, cta, team, homePage, catalog, productCategory, product, inquiry, businessNiche]
